### PR TITLE
[JS-168] [Build] Update to ember 3.12

### PR DESCRIPTION
**Pull request by romgere**
Update to ember 3.12 : 
- Update to ember 3.4
- Fix lint errors
- Update ember to 3.8 & update eslint-config-peopledoc to 1.7.2
- remove node 6 support, not compatible with "server" stuff
- fix lint errors
- update ember-concurrency to lastest supported by depencies
- Remove "ember-route-action-helper" & move action to controller
- update ember-bootstrap to v2.8.0 to avoid "ember-copy" deprecated
- Update to ember 3.12
- update ember-bootstrap-power-select, ember-power-select Remove useless ember-power-select-blockless & fix power-select "onChange" error
- fix computed override warning with ember-overridable-computed
- remove ember-simple-auth (useless & prevent deprecated warning)

:information_source: Since there are not working tests, this PR is tested manually by runing the app. The graph are correctly rendered, I can navigate in repo & branches and I can create custom graph.

### CODE REVIEW

**Comment by xcambar** [comment]
Did the tests fail only for this PR or were they failing already with your base commit?

**Comment by romgere** [comment]
They failed before my modifications, there is no tests on this app & auto-generated tests are failing too.

**Comment by xcambar** [comment]
ping @njoyard can you fix this, please? You're the latest commiter on `master` ;)

**Comment by GreatWizard** [comment]
Close in favor of https://github.com/peopledoc/perfo/pull/13

**Pull request closed without merging**
